### ISSUE TITLE
port to 1.18.2

### ISSUE THREAD

**Issue by xHBRD** [Mr-Zombii/KeybindCFG#1]
Hi Mr.Zombii! hope to find you well, have you thought of expanding the version compatibility of the mod? i'm making a 1.18.2 modpack and i would love to use your mod!

Best regards,

Fred.

**Comment by Mr-Zombii** [comment]
Hi Fred, I would love to port this to 1.18.2 or any version requested, and maybe any loader aswell. I will start porting this down now :D.

**Comment by Mr-Zombii** [comment]
Also I am uploading it on curseforge for people who need it there aswell :D

**Comment by xHBRD** [comment]
Wow, didn't expected a response THAT FAST! I am absolutely loving your passion, you're absolutely invited to try the modpack on curseforge, it's called "Hardpath: Embrace endurance", i'll wait for the keybindCFG port to 1.18.2. Furthermore, i would love to support you, consider adding your paypal when uploading the mod to CurseForge!

**Comment by Mr-Zombii** [comment]
Well, I could have responded faster. I originally saw this an hour after is was posted. Also i'm almost done working on it but hitting some issues, but they aren't anything I can't resolve :)

**Comment by Mr-Zombii** [comment]
![image](https://github.com/user-attachments/assets/541fc338-50aa-43dd-ac7d-4fb5fa5ca113)

**Comment by Mr-Zombii** [comment]
![image](https://github.com/user-attachments/assets/f889d91c-318b-48ec-adc5-f3828c223c7f)

**Comment by Mr-Zombii** [comment]
Here ya go :D

https://modrinth.com/mod/keybind-cfg/version/JPwpcwJq

**Comment by Mr-Zombii** [comment]
Reuploaded 1.18.2 :D

https://modrinth.com/mod/keybind-cfg/version/9POhlnzr

**Comment by Mr-Zombii** [comment]
It will be on curseforge in a couple days since their verification process is slow but its up on modrinth @xHBRD

**Comment by Mr-Zombii** [comment]
What will be available in a few days. 
![image](https://github.com/user-attachments/assets/a0b21eee-ffbb-4da6-a76a-a39db9e6accb)

**Comment by xHBRD** [comment]
Thank you so much, can't wait to see it on Curseforge, i'm downloading it rn via modrinth

**Comment by xHBRD** [comment]
i'm having a little problem, when i open keybind options it crash with the next crashlog
[crash-2024-09-02_21.58.19-client.txt](https://github.com/user-attachments/files/16842177/crash-2024-09-02_21.58.19-client.txt)

hope you know how to read it and help me solve the incompatibility

**Comment by Mr-Zombii** [comment]
try using https://modrinth.com/mod/architectury-api

**Comment by Mr-Zombii** [comment]
it may be needed

**Comment by Mr-Zombii** [comment]
I am currently figuring out how to fix it

**Comment by Mr-Zombii** [comment]
I think I found a way to fix it

**Comment by Mr-Zombii** [comment]
I FIXED IT :DDDD

**Comment by xHBRD** [comment]
WOW DUDE, AMAZING! I'll check it when i get back home!!

**Comment by Mr-Zombii** [comment]
https://modrinth.com/mod/keybind-cfg/version/1.0.1

https://legacy.curseforge.com/minecraft/mc-mods/keybind-cfg/files/5690793

**Comment by Mr-Zombii** [comment]
![image](https://github.com/user-attachments/assets/a4b50f32-9077-4eff-a1bc-dd29e2f3e0a3)

**Comment by Mr-Zombii** [comment]
yo, curseforge approved it

**Comment by xHBRD** [comment]
Amazing work, i'll try it when i get back home

**Comment by xHBRD** [comment]
I'm testing it rn, it works perfect! What an amazing job.
