### ISSUE TITLE
Incompatibility with Sinytra Connector

### ISSUE THREAD

**Issue by NuruddinPlays** [Mr-Zombii/KeybindCFG#2]
Hi! So I tried using this mod for a modpack I was making, and for some reason this mod is not compatible with Sinytra Connector. When I tried to open the game, the game crashes during game load when both mods are enabled.

I've already reported the problem to Sinytra Connector's issue page, including a log, crash report and steps to reproduce here: https://github.com/Sinytra/Connector/issues/1497

**Comment by Mr-Zombii** [comment]
I will fix this using your crashreport and have a build out soon. Thank you for the info.

**Comment by Mr-Zombii** [comment]
Fixed in version 1.0.1 - 1.20.1
https://modrinth.com/mod/keybind-cfg/version/VX0U0CHb
