### ISSUE TITLE
Incompatibilities with mods that add tooltips to the keybind screen

### ISSUE THREAD

**Issue by NuruddinPlays** [Mr-Zombii/KeybindCFG#3]
While these are two very separate mods, I decided to group them because the cause of crash is the same

After the problem with Sinytra got fixed, I tried to use this mod for the modpack I talked about, and I found out that it crashed when accessing the keybind screen with either one of those mods enabled. Most likely because those mods also added their own set of tooltips to the keybind screen

MC Version: 1.20.1
Forge Version: 47.3.11
KeybindCFG Version: 1.0.1

## Beans Backpacks - https://modrinth.com/mod/beans-backpacks
Version: 2.0.2
Crash Report & debug.log : https://gist.github.com/NuruddinPlays/60a92c8bcda79b0be30351dc545b07ac

## Create: Steam 'n' Rails - https://modrinth.com/mod/create-steam-n-rails
Version: 1.6.7
Crash Report & debug.log : https://gist.github.com/NuruddinPlays/2518ead410734240162f3c61051c691d
Requires Create - https://modrinth.com/mod/create (Version 0.5.1)

## Note
Since the project that used said modpack started very soon at the time of the Sinytra fix, I simply disabled the problematic mixins within both mods, but this is pretty much not a permanent solution. Hopefully you can fix this problem so I can later distribute the modpack with the unmodified mod files

**Comment by Mr-Zombii** [comment]
Sorry that i took a while to reply, I was busy with some other projects. Now that I am avalible I will take a look and see if i can fix it :).

**Comment by Mr-Zombii** [comment]
![image](https://github.com/user-attachments/assets/9c06f768-1503-426e-9064-7d8cf2dea712)

**Comment by Mr-Zombii** [comment]
okay, I changed how the mixin applied and was organized for the update and it works with both mods now.

**Comment by Mr-Zombii** [comment]
https://modrinth.com/mod/keybind-cfg/version/knTUhz1j

**Comment by NuruddinPlays** [comment]
Hey! Sorry for the late reply, but I have tested and confirmed that version 1.0.2 works with the two mods above! Thank you so much! ❤️

**Comment by Mr-Zombii** [comment]
Yw & have a great day :D.
