### ISSUE TITLE
1.12.2 backport

### ISSUE THREAD

**Issue by sunshinekitsune** [Mr-Zombii/KeybindCFG#4]
Could you consider backporting this mod to 1.12.2? I'd do it myself but I don't know how :p

**Comment by Mr-Zombii** [comment]
I can attempt a 1.12.2 backport for ya when I have the time.

**Comment by Mr-Zombii** [comment]
it was pain, but I got the keybinds to save in a file called `keybinds_1.12.2.json` instead of `keybinds.json`

**Comment by Mr-Zombii** [comment]
https://modrinth.com/mod/keybind-cfg/version/1.0.2-1.12.2
